name: HQS build docs for all packages

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  publish_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip maturin
        pip install struqture_qutip_interface/[docs] struqture_qutip_interface_devices/[docs]
    - uses: peaceiris/actions-mdbook@v1
      with:
        version: latest
    - name: build
      run: |
        # struqture_qutip_interface
        cd struqture_qutip_interface/docs
        python -m sphinx -T -E -b html . _build/html
        cd ../../
        cp -r ./struqture_qutip_interface/docs/_build/html ./documentation/src/struqture_qutip_interface_api
        # struqture_qutip_interface_devices
        cd struqture_qutip_interface_devices/docs
        python -m sphinx -T -E -b html . _build/html
        cd ../../
        cp -r ./struqture_qutip_interface_devices/docs/_build/html ./documentation/src/struqture_qutip_interface_devices_api
        # rostruqture_qutip_interface_devices
        cargo doc --no-deps --package=rostruqture_qutip_interface_devices
        cp -r ./target/doc/* ./documentation/src/rostruqture_qutip_interface_devices_api
        # Generating doc
        cd documentation/
        mdbook build

    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: documentation/book